### ISSUE TITLE
mooc-flight-theory

### ISSUE THREAD

**Issue by marcovanderbijl** [johanjan/icarus#1]
Hi,
Sorry for posting this question here but I did not really know another way of reaching out to somebody in the 'new theory of flight' group.
On this page; https://secretofflight.wordpress.com/mooc-flight-theory/ it is said that a new MassiveOpenOnlineCourse was planned for February 2020. I am really interested in attending that course. But have been unable to find out more (starting date, which online platform, etc). As Feb2020 is rapidly approaching I was hoping you could give me some more information.
Thank you,
Marco vanderBijl

**Comment by marcovanderbijl** [comment]
found https://www.edx.org/course/high-performance-finite-element-modeling?utm_source=sailthru&utm_medium=email&utm_campaign=triggered_shareit

**Comment by johanjan** [comment]
Hi Marcio, thanks a lot for your interest! 

We are planning to launch a new round in March. Could you write your email and I will keep you updated?

Best,
  Johan

**Comment by marcovanderbijl** [comment]
I am now enrolled in both
High Performance Finite Element Modeling KTHx - HPFEM01.1x Starts - Mar 3, 2020
https://www.edx.org/course/high-performance-finite-element-modeling
and
High Performance Finite Element Modeling – Part 2 KTHx - HPFEM02.1x Starts - Mar 17, 2020
https://www.edx.org/course/high-performance-finite-element-modeling-part-2
So I think I am all ready to go,
Unless more/other courses are planned than the above mentioned?
Great that you guys are organizing these courses, thank you!
I hope I'll be a good student,
Marco
